/**
 * Constante centralisée de tous les libellés de l'interface utilisateur.
 * Organisée par domaine fonctionnel. Importée par ComposantBase pour les composants partagés,
 * et déclarée localement dans chaque composant d'écran.
 */
export const LIBELLES = {
  /** Noms français des jours, indexés comme `Date.getDay()` (0 = dimanche). */
  dates: {
    nomsJours: ['dimanche', 'lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi'],
    initialeJours: ['D', 'L', 'M', 'M', 'J', 'V', 'S'],
  },

  /** Libellés communs réutilisés dans plusieurs domaines. */
  commun: {
    enregistrer: 'Enregistrer',
    annuler: 'Annuler',
    supprimer: 'Supprimer',
    modifier: 'Modifier',
    creer: 'Créer',
    confirmer: 'Confirmer',
    imprimer: 'Imprimer',
    fermer: 'Fermer',
    ajouter: 'Ajouter',
    vider: 'Vider',
    dupliquer: 'Dupliquer',
    charger: 'Charger',
    chargement: 'Chargement…',
    rechercher: 'Rechercher…',
    aucunResultat: 'Aucun résultat',
    avertissementModifications:
      'Des modifications non enregistrées seront perdues. Voulez-vous continuer ?',
  },

  /** Libellés de la barre d'en-tête. */
  entete: {
    titre: 'MaClasse',
    sauvegarder: 'Sauvegarder',
    refaire: 'Refaire',
    annuler: 'Annuler',
    tooltipDerniereSauvegarde: 'Dernière sauvegarde : ',
    tooltipAucuneSauvegarde: 'Aucune sauvegarde effectuée',
    tooltipPrefixeAnnuler: 'Annuler : ',
    tooltipPrefixeRefaire: 'Refaire : ',
    rechercheLabel: 'Recherche globale',
    rechercheAria: 'Résultats de recherche',
    boutonTheme: 'Changer de thème',
    tooltipNavRestreinte:
      'Pour accéder à ces fonctionnalités, créer un jeu de données après avoir recharger la page',
  },

  /** Libellés de la navigation principale. */
  navigation: {
    accueil: 'Accueil',
    eleves: 'Élèves',
    projets: 'Projets',
    competences: 'Compétences',
    emploiDuTemps: 'Emploi du temps',
    cahierJournal: 'Cahier journal',
    parametrage: 'Paramétrage',
  },

  /** Libellés de l'écran de démarrage (popin obligatoire). */
  demarrage: {
    bienvenue: 'Bienvenue dans MaClasse — gérez votre classe, à votre façon.',
    titreNouveau: 'Première utilisation ?',
    texteNouveau: "Créez votre espace de classe à partir d'un jeu de données d'exemple.",
    boutonCreer: "Créer ma classe à partir d'un jeu de données d'exemple",
    titreCharger: 'Sélectionner la dernière version des données de votre classe',
    labelFichier: 'Fichier ZIP',
    boutonParcourirFichier: 'Parcourir…',
    labelMotDePasse: 'Mot de passe',
    boutonCharger: 'Charger',
    boutonChargement: 'Chargement…',
    titreReferentiel: 'Référentiel de compétences',
    texteReferentiel:
      "L'application contient un référentiel des compétences issues des BO de l'EN.",
    boutonReferentiel: 'Accéder aux programmes',
    erreurFichier: 'Fichier invalide ou corrompu.',
    erreurMotDePasse: 'Mot de passe incorrect.',
    erreurVersionIncompatible:
      "Ce fichier a été créé avec une version plus récente de MaClasse. Veuillez mettre à jour l'application.",
  },

  /** Libellés de l'écran Accueil. */
  accueil: {
    labelAujourdhui: "AUJOURD'HUI",
    aucunJournal: "Aucun journal pour aujourd'hui",
    labelNbEleves: 'élève(s)',
  },

  /** Libellés de l'écran Élèves. */
  eleve: {
    titre: 'Élèves',
    boutonCreer: 'Créer un élève',
    aucunEleve: 'Aucun élève dans la classe',
    aucunEleveSelectionne: 'Sélectionnez un élève ou créez-en un nouveau.',
    boutonImprimer: 'Imprimer la fiche',
    sectionIdentite: 'Identité',
    sectionContacts: 'Contacts',
    sectionAbsencesRecurrentes: 'Absences récurrentes',
    sectionAbsencesPonctuelles: 'Absences ponctuelles',
    sectionCursus: 'Cursus',
    sectionNotes: 'Notes administratives',
    labelPrenom: 'Prénom',
    labelNom: 'Nom',
    labelSexeM: 'Masculin',
    labelSexeF: 'Féminin',
    labelDateNaissance: 'Date de naissance',
    labelDateArrivee: "Date d'arrivée",
    labelNiveau: 'Niveau',
    labelGroupes: 'Groupes',
    labelStatut: 'Statut',
    labelBilans: 'Bilans',
    labelAccueil: 'Accueil',
    labelInclusion: 'Inclusion',
    labelContactType: 'Type',
    labelContactNom: 'Nom',
    labelContactEmail: 'Email',
    labelContactTelephone: 'Téléphone',
    labelContactAdresse: 'Adresse postale',
    boutonAjouterContact: 'Ajouter un contact',
    labelAbsenceLibelle: 'Libellé',
    labelAbsenceJour: 'Jour',
    labelAbsenceHeureDebut: 'Heure de début',
    labelAbsenceHeureFin: 'Heure de fin',
    labelAbsenceParite: 'Fréquence',
    boutonAjouterAbsenceRec: 'Ajouter une absence récurrente',
    labelAbsenceDate: 'Date',
    labelAbsenceJustification: 'Justification',
    boutonAjouterAbsencePonct: 'Ajouter une absence ponctuelle',
    labelCursusAnnee: 'Année scolaire',
    labelCursusNiveau: 'Niveau',
    labelCursusEtablissement: 'Établissement',
    labelCursusAccompagnement: 'Accompagnement',
    boutonAjouterCursus: 'Ajouter une année',
    labelDroitImage: "Droit à l'image",
    labelAutorisationBaignade: 'Autorisation baignade',
    labelPPA: 'Autres',
    labelESS: 'ESS',
    labelSexe: 'Sexe',
    ariaListeEleves: 'Liste des élèves',
  },

  /** Libellés de l'écran Projets. */
  projet: {
    titre: 'Projets',
    boutonCreer: 'Créer un projet',
    aucunProjet: 'Aucun projet',
    aucunProjetSelectionne: 'Sélectionnez un projet ou créez-en un nouveau.',
    boutonImprimer: 'Imprimer le projet',
    sectionInfos: 'Informations générales',
    sectionPeriodes: 'Périodes',
    labelNom: 'Nom du projet',
    labelDescription: 'Description',
    labelEleves: 'Élèves associés',
    labelPeriodeNom: 'Nom de la période',
    labelPeriodeDebut: 'Date de début',
    labelPeriodeFin: 'Date de fin',
    labelPeriodeDescription: 'Description de la période',
    labelPeriodeCompetences: 'Compétences',
    boutonAjouterPeriode: 'Ajouter une période',
    ariaListeProjets: 'Liste des projets',
  },

  /** Libellés de l'écran Compétences. */
  competences: {
    titre: 'Compétences',
    panierVide: 'Aucune compétence sélectionnée',
    boutonVider: 'Vider la liste',
    boutonEnvoyerProjet: 'Envoyer vers un projet',
    boutonEnvoyerSeance: 'Envoyer vers une séance',
    infoDomainesParametrage:
      "Tous les domaines sont disponibles et activables dans l'écran Paramétrage.",
    ariaAjouterAuPanier: 'Ajouter au panier : ',
    ariaPanier: 'Panier de compétences',
    ariaRetirer: 'Retirer ',
    ariaReplierNoeud: 'Replier ',
    ariaDeplierNoeud: 'Déplier ',
  },

  /** Libellés du composant sélecteur de compétences (`mc-selecteur-competences`). */
  selecteurCompetences: {
    placeholder: 'Rechercher une compétence…',
    ariaFiltreDomaine: 'Filtrer par domaine',
    ariaSuggestions: 'Suggestions de compétences',
    ariaSelectionnes: 'Compétences sélectionnées',
    ariaSupprimer: 'Supprimer la compétence : ',
  },

  /** Libellés de l'écran Emploi du temps. */
  edt: {
    titre: 'Emploi du temps',
    boutonCreer: 'Créer un emploi du temps',
    boutonImprimer: 'Imprimer',
    aucunEdtSelectionne: 'Sélectionnez un emploi du temps ou créez-en un.',
    avertissementChevauchement: "Un conflit d'absence a été détecté.",
    labelNom: "Nom de l'emploi du temps",
    labelDateDebut: 'Date de début',
    labelDateFin: 'Date de fin',
    labelFrequence: 'Fréquence',
    frequencePaire: 'Semaines paires',
    frequenceImpaire: 'Semaines impaires',
    frequenceLesDeux: 'Toutes les semaines',
    labelHeureDebut: 'Heure de début',
    labelHeureFin: 'Heure de fin',
    labelType: 'Type',
    labelDisciplines: 'Disciplines',
    labelTitreCreneau: 'Titre',
    labelEleves: 'Élèves concernés',
    typePedagogique: 'Pédagogique',
    typeRecreation: 'Récréation',
    typePauseDejeuner: 'Pause déjeuner',
    boutonAjouter: 'Ajouter un créneau',
    aucunCreneau: 'Aucun créneau',
    ariaListeEdt: 'Liste des emplois du temps',
    ariaGrilleHebdomadaire: 'Grille hebdomadaire',
    colonneHeure: 'Heure',
    suffixeCreneau: 'créneau',
    joursLibelles: {
      lundi: 'Lundi',
      mardi: 'Mardi',
      mercredi: 'Mercredi',
      jeudi: 'Jeudi',
      vendredi: 'Vendredi',
    },
  },

  /** Libellés de l'écran Cahier journal. */
  cahierJournal: {
    titre: 'Cahier journal',
    boutonInitialiserVide: 'Initialiser une journée vide',
    boutonInitialiserEdt: "Initialiser depuis l'emploi du temps",
    boutonSupprimerJournee: 'Supprimer la journée',
    boutonDupliquerSeance: 'Dupliquer la séance',
    boutonDupliquerJournee: 'Dupliquer la journée',
    boutonConfirmerDuplication: 'Confirmer la duplication',
    boutonImprimer: 'Imprimer',
    aucuneSeance: 'Aucune séance pour cette journée',
    labelJourCible: 'Jour cible',
    avertissementRemplacement:
      'Le jour cible contient déjà des séances. Voulez-vous les remplacer ?',
    labelHeureDebut: 'Heure de début',
    labelHeureFin: 'Heure de fin',
    labelType: 'Type',
    labelNotes: 'Notes de la journée',
    placeholderNotes: 'Rappels, événements, absents, matériel à prévoir…',
    labelDisciplines: 'Disciplines',
    labelTitre: 'Titre',
    labelDescription: 'Description',
    labelObjectifs: 'Objectifs',
    labelDeroulement: 'Déroulement',
    labelRessources: 'Ressources',
    labelCompetences: 'Compétences',
    labelEleves: 'Élèves concernés',
    suffixeSeance: 'une séance',
    boutonAjouterSeance: 'Ajouter une séance',
    tooltipMoins7Jours: '-7 jours',
    ariaMoins7Jours: '7 jours en arrière',
    tooltipMoins1Jour: '-1 jour',
    ariaJourPrecedent: 'Jour précédent',
    tooltipPlus1Jour: '+1 jour',
    ariaJourSuivant: 'Jour suivant',
    tooltipPlus7Jours: '+7 jours',
    ariaPlus7Jours: '7 jours en avant',
    ariaDuplication: 'Duplication',
    ariaMonterSeance: 'Monter la séance',
    ariaDescendreSeance: 'Descendre la séance',
    ariaModifierSeance: 'Modifier la séance',
    ariaSupprimerSeance: 'Supprimer la séance',
  },

  /** Libellés de l'écran Paramétrage. */
  parametrage: {
    titre: 'Paramétrage',
    sections: {
      enseignantClasse: 'Enseignant & Classe',
      periodes: 'Périodes scolaires',
      semaineHoraires: 'Semaine & Horaires',
      groupes: 'Groupes',
      bareme: "Barème d'évaluation",
      statutsEleve: 'Statuts élève',
      typesContact: 'Types de contact',
      raisonsAbsence: "Raisons d'absence",
      frequencesAbsence: "Fréquences d'absence",
      joursFeries: 'Jours fériés',
      preferences: 'Préférences',
      domainesCompetences: 'Domaines de compétences',
    },
    labelPrenom: 'Prénom',
    labelNom: 'Nom',
    labelAnnee: 'Année scolaire',
    labelNiveauClasse: 'Niveau de la classe',
    labelJoursOuvres: 'Jours ouvrés',
    labelHeureDebutJournee: 'Heure de début de journée',
    labelHeureFinJournee: 'Heure de fin de journée',
    labelGroupeId: 'Identifiant',
    labelGroupeLibelle: 'Libellé',
    labelPeriodeNom: 'Nom',
    labelPeriodeDebut: 'Date de début',
    labelPeriodeFin: 'Date de fin',
    labelStatutId: 'Identifiant',
    labelStatutGlyphe: 'Glyphe',
    labelStatutLibelle: 'Libellé',
    labelStatutCouleur: 'Couleur texte',
    labelStatutFond: 'Couleur fond',
    labelStatutApercu: 'Aperçu',
    labelStatutEleveId: 'Identifiant',
    labelStatutEleveLibelle: 'Libellé',
    labelTypeContactId: 'Identifiant',
    labelTypeContactLibelle: 'Libellé',
    labelRaisonLibelle: 'Libellé',
    labelFrequenceId: 'Identifiant',
    labelFrequenceLibelle: 'Libellé',
    labelJourFerieNom: 'Nom',
    labelJourFerieDate: 'Date',
    labelDelaiSauvegarde: 'Délai de sauvegarde automatique (minutes)',
    tooltipValeurUtilisee: 'Cette valeur est utilisée et ne peut pas être supprimée',
    labelDomainesInfo:
      'Cochez les domaines et sous-domaines à utiliser dans votre classe. Décochez tout pour tout afficher.',
    ariaCheckboxDomaine: 'Activer le domaine',
    ariaCheckboxSousDomaine: 'Activer le sous-domaine',
    ariaSectionsParametrage: 'Sections de paramétrage',
  },

  /** Libellés des fenêtres modales (popins). */
  popins: {
    /** Popin de confirmation avant perte de données. */
    avertissement: {
      titre: 'Attention',
      confirmer: 'Continuer sans enregistrer',
      annuler: 'Rester sur la page',
    },
    /** Popin de saisie du mot de passe lors de la première sauvegarde. */
    sauvegarde: {
      titre: 'Première sauvegarde',
      labelMotDePasse: 'Mot de passe de chiffrement',
      confirmer: 'Sauvegarder',
      annuler: 'Annuler',
    },
    /** Popin d'affichage des conflits d'absences. */
    warnings: {
      titre: 'Conflits détectés',
      fermer: 'Fermer',
    },
    /** Popin d'export de compétences vers un projet ou une séance. */
    exportCompetences: {
      titre: 'Exporter les compétences',
      choixProjet: 'Projet',
      choixPeriode: 'Période',
      choixJour: 'Jour',
      choixSeance: 'Séance',
      confirmer: 'Exporter',
      annuler: 'Annuler',
    },
  },

  /** Libellés du composant `mc-eleves-concernes` (modes de sélection). */
  elevesConcernes: {
    legende: 'Périmètre des élèves concernés',
    modeClasse: 'Toute la classe',
    modeGroupes: 'Par groupes',
    modeEleves: 'Élèves spécifiques',
    ariaGroupes: 'Groupes',
    ariaEleves: 'Élèves',
  },

  /** Libellés des actions soumises au mécanisme UNDO/REDO, affichés dans les tooltips. */
  commandes: {
    ajoutEleve: "Ajout d'un élève",
    modificationEleve: "Modification d'un élève",
    suppressionEleve: "Suppression d'un élève",
    ajoutProjet: "Ajout d'un projet",
    modificationProjet: "Modification d'un projet",
    suppressionProjet: "Suppression d'un projet",
    ajoutPeriodeProjet: "Ajout d'une période",
    modificationPeriodeProjet: "Modification d'une période",
    suppressionPeriodeProjet: "Suppression d'une période",
    ajoutEdt: "Ajout d'un emploi du temps",
    modificationEdt: "Modification d'un emploi du temps",
    suppressionEdt: "Suppression d'un emploi du temps",
    ajoutCreneau: "Ajout d'un créneau",
    modificationCreneau: "Modification d'un créneau",
    suppressionCreneau: "Suppression d'un créneau",
    initialisationJourneeVide: "Initialisation d'une journée vide",
    initialisationDepuisEdt: "Initialisation depuis l'EDT",
    modificationNotesJournee: "Modification des notes d'une journée",
    ajoutSeance: "Ajout d'une séance",
    modificationSeance: "Modification d'une séance",
    suppressionSeance: "Suppression d'une séance",
    reordonnancementSeances: 'Réordonnancement de séances',
    suppressionJournee: "Suppression d'une journée",
    duplicationSeance: "Duplication d'une séance",
    duplicationJournee: "Duplication d'une journée",
    ajoutGroupe: "Ajout d'un groupe",
    modificationGroupe: "Modification d'un groupe",
    suppressionGroupe: "Suppression d'un groupe",
    ajoutStatutAcquisition: "Ajout d'un statut d'acquisition",
    modificationStatutAcquisition: "Modification d'un statut d'acquisition",
    suppressionStatutAcquisition: "Suppression d'un statut d'acquisition",
    ajoutStatutEleve: "Ajout d'un statut élève",
    modificationStatutEleve: "Modification d'un statut élève",
    suppressionStatutEleve: "Suppression d'un statut élève",
    ajoutTypeContact: "Ajout d'un type de contact",
    modificationTypeContact: "Modification d'un type de contact",
    suppressionTypeContact: "Suppression d'un type de contact",
    ajoutRaisonAbsence: "Ajout d'une raison d'absence",
    modificationRaisonAbsence: "Modification d'une raison d'absence",
    suppressionRaisonAbsence: "Suppression d'une raison d'absence",
    ajoutFrequenceAbsence: "Ajout d'une fréquence d'absence",
    modificationFrequenceAbsence: "Modification d'une fréquence d'absence",
    suppressionFrequenceAbsence: "Suppression d'une fréquence d'absence",
    ajoutPeriode: "Ajout d'une période scolaire",
    modificationPeriode: "Modification d'une période scolaire",
    suppressionPeriode: "Suppression d'une période scolaire",
    ajoutJourFerie: "Ajout d'un jour férié",
    modificationJourFerie: "Modification d'un jour férié",
    suppressionJourFerie: "Suppression d'un jour férié",
    modificationConfigEdt: 'Modification de la configuration EDT',
    modificationEnseignant: 'Modification des informations enseignant',
    modificationNiveauClasse: 'Modification du niveau de classe',
    modificationPreferences: 'Modification des préférences',
    modificationDomainesActifs: 'Modification des domaines actifs',
  },

  /** Libellés destinés exclusivement à l'accessibilité (RGAA). */
  aria: {
    boutonFermerPopin: 'Fermer la fenêtre',
    navigationPrincipale: 'Navigation principale',
    champRecherche: 'Champ de recherche',
    valeurUtiliseeNonSupprimable:
      "Cette valeur est utilisée dans l'application et ne peut pas être supprimée",
    eleveAbsent: 'Élève absent ce jour',
    calendrierMoisPrecedent: 'Mois précédent',
    calendrierMoisSuivant: 'Mois suivant',
  },
} as const;
